"""Runtime UI + export patch: BAD-D/ERSS appendix and morphology-row removal."""
from pathlib import Path
import re
import hc_age_policy, hc_bad_final_policy, bootstrap, extraction_guard, erss_topography_guard
import report_export_guard  # activates PDF/DOCX fixes before export endpoints are used
APP_VERSION="0.7.30"; APP_LABEL=f"HC Ectasia App v{APP_VERSION}"
index_path=Path(__file__).parent/"static"/"index.html"
CSS='''<style id="hc-reference-style">.hc-reference-appendix{margin-top:24px;border-top:2px solid #8aa0b8;padding-top:14px}.hc-reference-appendix h3{color:#173b57;margin:12px 0 6px}.hc-bad-normal{background:#e6f4ea!important;color:#176b3a!important;font-weight:bold}.hc-bad-suspicious{background:#fff0d8!important;color:#9a4d00!important;font-weight:bold}.hc-bad-abnormal{background:#fde5e5!important;color:#a31212!important;font-weight:bold}@media print{.hc-reference-appendix{display:block!important}.hc-bad-normal,.hc-bad-suspicious,.hc-bad-abnormal{-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style>'''
SCRIPT=r'''<script id="hc-reference-script">(function(){const html=`<section id="hcReferenceAppendix" class="hc-reference-appendix"><h3>HC BAD-D reference points</h3><table class="clinical-table"><thead><tr><th>Final BAD-D</th><th>HC interpretation / action</th></tr></thead><tbody><tr><td>≤ 1.6</td><td class="hc-bad-normal">NORMAL</td></tr><tr><td>&gt; 1.6 to &lt; 3.0</td><td class="hc-bad-suspicious">SUSPICIOUS — REVIEW / NOT CLEARED</td></tr><tr><td>≥ 3.0</td><td class="hc-bad-abnormal">ABNORMAL CORNEA — DO NOT PROCEED</td></tr></tbody></table><p class="note"><strong>BAD-D source:</strong> Pentacam BAD display; independent of Randleman/ERSS anterior-topography scoring.</p><h3>Randleman / ERSS scoring points</h3><table class="clinical-table"><thead><tr><th>Variable</th><th>Finding</th><th>Points</th></tr></thead><tbody><tr><td>Anterior topography</td><td>Normal / symmetrical</td><td>0</td></tr><tr><td>Anterior topography</td><td>Asymmetric bow-tie</td><td>1</td></tr><tr><td>Anterior topography</td><td>Inferior steepening / significant SRA-SRAX</td><td>3</td></tr><tr><td>Anterior topography</td><td>Abnormal ectatic pattern</td><td>4</td></tr><tr><td>Residual stromal bed</td><td>≥300 µm</td><td>0</td></tr><tr><td>Residual stromal bed</td><td>280–299 µm</td><td>1</td></tr><tr><td>Residual stromal bed</td><td>260–279 µm</td><td>2</td></tr><tr><td>Residual stromal bed</td><td>240–259 µm</td><td>3</td></tr><tr><td>Residual stromal bed</td><td>&lt;240 µm</td><td>4</td></tr></tbody></table><p class="note">Randleman anterior-topography points come only from the anterior curvature/topography image. On Pentacam 4 Maps Refractive this is the upper-left Axial/Sagittal Curvature (Front) panel.</p></section>`;function install(){const eyes=document.getElementById('eye-results'),footer=document.querySelector('#reportSheet .report-footer-note');if(!eyes||!footer||!eyes.children.length)return;if(!document.getElementById('hcReferenceAppendix'))footer.insertAdjacentHTML('beforebegin',html);document.querySelectorAll('tr').forEach(r=>{const c=r.querySelectorAll('td,th');if(c.length>=1&&['morphology category','morphology'].includes((c[0].textContent||'').trim().toLowerCase()))r.remove()})}let queued=false;function q(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;install()})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',q);else q();new MutationObserver(ms=>{if(ms.some(m=>m.addedNodes.length))q()}).observe(document.documentElement,{childList:true,subtree:true});})();</script>'''
try:
 html=index_path.read_text(encoding='utf-8');html=re.sub(r'HC Ectasia App v\d+\.\d+\.\d+',APP_LABEL,html);html=re.sub(r'Software v\d+\.\d+\.\d+',f'Software v{APP_VERSION}',html);html=re.sub(r'<style id="hc-reference-style">.*?</style>','',html,flags=re.S);html=re.sub(r'<script id="hc-reference-script">.*?</script>','',html,flags=re.S);html=html.replace('</head>',CSS+'\n</head>').replace('</body>',SCRIPT+'\n</body>');index_path.write_text(html,encoding='utf-8')
except OSError:pass
bootstrap.core.APP_VERSION=APP_VERSION;bootstrap.core.app.title=APP_LABEL;app=bootstrap.app
